---
Generators:
  -
    Id: freq
    Type: Sine
    Frequency: 4.0
  -
    Id: freqLerp
    Type: Lerp
    min: 100.0
    max: 10.0
    value: freq
  -
    Id: mainOsc
    Type: Sine
    Frequency: freqLerp

  -
    Id: beep.osc
    Type: Sine
    Frequency: basefrequency
  -
    Id: beep.duration
    Type: Pulse
    Frequency: length
  -
    Id: beep.main
    Type: Multiply
    in: [ beep.osc, beep.duration ]
  -
    Id: beep
    Type: Component
    inputs: [ basefrequency, length ]
    source: beep.main
  -
    Id: componentTest
    Type: Component
    inputs: [ frequency, length ]
    source:
      Id: blah
      Type: Sine
      frequency: frequency



  -
    Id: release.ramp
    Type: Ramp
    Time: time
  -
    Id: release.invert
    Type: Lerp
    value: release.ramp
    min: 1.0
    max: 0.0
  -
    Id: release.mult
    Type: Multiply
    in: [ audio, release.invert ]
  -
    Id: release
    Type: Component
    inputs: [ audio, time ]
    source: release.mult




  -
    Id: tremshape
    Type: Sine
    Frequency: 5.0
  -
    Id: tremapply
    Type: Multiply
    in: [ tremshape, audio ]
  -
    Id: tremalo
    Type: Component
    inputs: [ audio ]
    source: tremapply


  -
    Id: beep440
    Type: beep
    basefrequency: 440.0
    length: 1.0
  -
    Id: beep480
    Type: beep
    basefrequency: 140.0
    length: 1.0

  -
    Id: valuesweep.ramp
    Type: Ramp
    Time: time1
  -
    Id: valuesweep.lerp
    Type: Lerp
    Value: valuesweep.ramp
    min: start
    max: end
  -
    Id: valuesweep
    Type: Component
    inputs: [start, end, time1]
    source: valuesweep.lerp

  -
    Id: freqsweep
    Type: valuesweep
    start: 140.0
    end: 40.0
    time1: time
  -
    Id: clipsweep
    Type: valuesweep
    start: 0.15
    end: 2
    time1: time

  -
    Id: beepsweep
    Type: beep
    basefrequency: freqsweep
    length: time
  -
    Id: beepclipped
    Type: Hardclip
    in: beepsweep
    clip: clipsweep
  -
    Id: trembeep440
    Type: tremalo
    audio: beep440
  -
    Id: releasetest
    Type: release
    audio: beepclipped
    time: 0.9


  -
    Id: tremalo2.shape
    Type: Sine
    frequency: freq
  -
    Id: tremalo2.range
    Type: Lerp
    value: tremalo2.shape
    min: min
    max: max
  -
    Id: tremalo2
    Type: Component
    inputs: [ freq, min, max ]
    source: tremalo2.range


  -
    Id: delaytest
    Type: Delay
    delay: 11050
    duration: 2.0
    in: releasetest
  -
    Id: delaytremalo
    Type: tremalo2
    freq: 4
    min: 22000
    max: 22500
  -
    Id: delaytest2
    Type: Delay
    delay: 22000
    duration: 0
    in: releasetest

  -
    Id: mixer
    Type: Add
    in: [ releasetest, delaytest2 ]

  -
    Id: filtersweep
    Type: valuesweep
    start: 1000
    end: 400
    time1: 1.0
  -
    Id: resonancebounce
    Type: valuesweep
    start: 0
    end: 4
    time1: 0.5
  -
    Id: filter
    Type: FilterLadder
    in: mixer
    frequency: filtersweep
    resonance: resonancebounce
  -
    Id: mixerout
    Type: Multiply
    in: [ filter ]





  -
    Id: hihat.osc1
    Type: Noise
  -
    Id: hihat.oscpink
    value: hihat.white
    Type: Pinkify
  -
    Id: hihat.sine
    Type: Sine
    Frequency: 4185.6
  -
    Id: hihat.osc2
    Type: Sine
    Frequency: 4185.6
  -
    Id: hihat.osc2out
    Type: Multiply
    in: [ hihat.osc2, 0.25 ]
  -
    Id: hihat.mix
    Type: Add
    in : [ hihat.osc1, hihat.osc2out ]
  -
    Id: hihat.mix
    Type: Add
    in : [ hihat.osc, hihat.sine ]
  -
    Id: hihat.release
    Type: release
    time: 0.125
    audio: hihat.mix
  -
    Id: hihat.duration
    Type: Pulse
    Frequency: 8
  -
    Id: hihat.outmix
    Type: Multiply
    in: [ hihat.release, hihat.duration ]
  -
    Id: hihat.outfilter
    Type: FilterHigh
    in: hihat.outmix
    frequency: 4000
    resonance: 0.0
  -
    Id: hihat
    Type: Component
    source: hihat.outfilter

  -
    Id: hihattest
    Type: hihat

  -
    Id: snare.comb
    Type: FilterComb
    in: hihat.mix
    delay: 50
    feedback: 0.75

  -
    Id: sequencer
    Type: MidiChannel
    Channel: 1
    Component: hihat


Outputs:
  -
    Id: out1
    Type: audio
    Source: hihattest
    Source_nope: mixerout
